[package]
name = "gpm"
version = "0.1.0"
edition = "2024"

[dependencies]
confy = { version = "1.0.0", features = ["toml"] }
crossterm = "0.29.0"
directories = "6.0.0"
ratatui = "0.29.0"
serde = { version = "1.0.219", features = ["derive"] }
tui-tree-widget = "0.23.1"
